name: Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-automation
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      release_tag: dev
